#!/bin/bash


# Set decoration geometry
berryc border_width       3
berryc inner_border_width 0
berryc title_height       18
berryc edge_gap           12 12 12 12

# Set decoration colors
berryc focus_color         e0b4f0
berryc unfocus_color       181824
berryc inner_focus_color   e0b4f0
berryc inner_unfocus_color 181824
berryc text_focus_color    242430
berryc text_unfocus_color  f0f0f0

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-12"

